# Generated by Django 5.0.3 on 2024-05-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_password_user_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Babie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('brought_by', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=6)),
                ('parent_name', models.CharField(max_length=100)),
                ('fee', models.FloatField()),
                ('period_of_stay', models.CharField(max_length=100)),
                ('baby_number', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('sitter', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby', models.CharField(max_length=100)),
                ('name_of_person', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date_of_Birth', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('next_of_kin', models.CharField(max_length=100)),
                ('nin', models.CharField(max_length=100)),
                ('reccomender_name', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100, null=True)),
                ('level_of_education', models.CharField(max_length=100)),
                ('sitter_number', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
    ]
