# Generated by Django 5.0.3 on 2024-05-09 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_babie_pickup_sitter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitter',
            old_name='reccomender_name',
            new_name='recomender_name',
        ),
    ]
