# Generated by Django 5.0.3 on 2024-05-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_reccomender_name_sitter_recomender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitter',
            name='on_duty',
            field=models.BooleanField(default=False),
        ),
    ]
