# Generated by Django 5.0.3 on 2024-05-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_sitter_on_duty'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='comment',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
